export const GET_CONNECTED_USER = "GET_CONNECTED_USER";
export const GET_USER_INFORMATIONS = 'GET_USER_INFORMATIONS';
export const UPDATE_USER_LEVEL = "UPDATE_USER_LEVEL";
export const UPDATE_USER_PROGRESS = 'UPDATE_USER_PROGRESS';
export const UPDATE_USER_CURRENT_INDEX = 'UPDATE_USER_CURRENT_INDEX';
export const UPDATE_USER_POINTS = 'UPDATE_USER_POINTS';
export const UPDATE_QIZZ_QUESTIONS = 'UPDATE_QIZZ_QUESTIONS';
export const UPDATE_USER_CHECKED_TRUE_ANSWER = 'UPDATE_USER_CHECKED_TRUE_ANSWER';
export const UPDATE_USER_CHECKED_FALSE_ANSWER = 'UPDATE_USER_CHECKED_TRUE_ANSWER';
export const UPDATE_USER_CHECK_TRUE_ANSWER = 'UPDATE_USER_CHECK_TRUE_ANSWER';
export const UPDATE_USER_PLAYING_QUIZZ = 'UPDATE_USER_PLAYING_QUIZZ';
export const UPDATE_USER_FOUND_ANSWER = 'UPDATE_USER_FOUND_ANSWER';
export const UPDATE_USER_ON_QUIZZ_SUMMARY_PAGE = 'UPDATE_USER_ON_QUIZZ_SUMMARY_PAGE';
export const UPDATE_QUIZZ_NEXT_INDEX = 'UPDATE_QUIZZ_NEXT_INDEX';
export const UPDATE_USER_NOT_FOUND_ANSWER = 'UPDATE_USER_NOT_FOUND_ANSWER';
export const UPDATE_USER_POINTS_ANAS = 'UPDATE_USER_POINTS_ANAS';
export const GET_ERROR_CONTEXT = 'GET_ERROR_CONTEXT';
export const UPDATE_USER_COURSES = 'UPDATE_USER_COURSES';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_USER_ETABLISSEMENT = 'UPDATE_USER_ETABLISSEMENT';
export const UPDATE_USER_FIRSTNAME = 'UPDATE_USER_FIRSTNAME';
export const UPDATE_USER_LASTNAME = 'UPDATE_USER_LASTNAME';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
















