export const GET_CONNECTED_USER = "GET_CONNECTED_USER";
export const GET_USER_INFORMATIONS = 'GET_USER_INFORMATIONS';
export const UPDATE_USER_LEVEL = "UPDATE_USER_LEVEL";
export const UPDATE_USER_PROGRESS = 'UPDATE_USER_PROGRESS';
export const UPDATE_USER_CURRENT_INDEX = 'UPDATE_USER_CURRENT_INDEX';
export const UPDATE_USER_POINTS = 'UPDATE_USER_POINTS';
