export const GET_CONNECTED_USER = "GET_CONNECTED_USER";
export const GET_USER_INFORMATIONS = 'GET_USER_INFORMATIONS';
export const UPDATE_USER_LEVEL = "UPDATE_USER_LEVEL";
export const UPDATE_USER_PROGRESS = 'UPDATE_USER_PROGRESS';
export const UPDATE_USER_CURRENT_INDEX = 'UPDATE_USER_CURRENT_INDEX';
export const UPDATE_USER_POINTS = 'UPDATE_USER_POINTS';
export const UPDATE_QIZZ_QUESTIONS = 'UPDATE_QIZZ_QUESTIONS';
export const UPDATE_USER_CHECKED_TRUE_ANSWER = 'UPDATE_USER_CHECKED_TRUE_ANSWER';
export const UPDATE_USER_CHECKED_FALSE_ANSWER = 'UPDATE_USER_CHECKED_TRUE_ANSWER';
export const UPDATE_USER_CHECK_TRUE_ANSWER = 'UPDATE_USER_CHECK_TRUE_ANSWER';
export const UPDATE_USER_PLAYING_QUIZZ = 'UPDATE_USER_PLAYING_QUIZZ';
export const UPDATE_USER_FOUND_ANSWER = 'UPDATE_USER_FOUND_ANSWER';
export const UPDATE_USER_ON_QUIZZ_SUMMARY_PAGE = 'UPDATE_USER_ON_QUIZZ_SUMMARY_PAGE';
export const UPDATE_QUIZZ_NEXT_INDEX = 'UPDATE_QUIZZ_NEXT_INDEX';
export const UPDATE_USER_POINTS_ANAS = 'UPDATE_USER_POINTS_ANAS';













