export const SET_LEVELS = 'SET_LEVELS';

export const FETCH_LEVELS_LOADING = 'FETCH_LEVELS_LOADING';
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS';
export const FETCH_LEVELS_ERROR = 'FETCH_LEVELS_ERROR';
